### ISSUE TITLE
Add option to customise text displayed in marker

### ISSUE THREAD

**Issue by daviewales** [goiblas/Map-Block-Leaflet#1]
Currently, the Leaflet marker displays the address which was entered to locate the marker.

It would be nice to be able to change what is displayed in the marker without changing the location of the marker.

**Comment by goiblas** [comment]
You can change the text the tooltip content from the sidebar
It is certainly not very clear, in the next update I will improve that.

**Comment by daviewales** [comment]
Thanks!
