### ISSUE TITLE
Map Block Leaflet 1.5 doesn't load.

### ISSUE THREAD

**Issue by daviewales** [goiblas/Map-Block-Leaflet#21]
After upgrading to version 1.5, Wordpress seems unable to detect this plugin.

Specifically, the plugin appears to be installed and activated, but I am unable to find it in the list of blocks. Blocks added with a previous version of the plugin no longer work.

**Comment by goiblas** [comment]
The way of loading the assets has changed only load when there is a map in the content.
I've tried it in the latest version, what WordPress versiondo you use?

**Comment by daviewales** [comment]
I'm running WordPress 5.2.2 and PHP 7.2.13.

**Comment by daviewales** [comment]
OK. I'm not quite sure what's happened here. It's mysteriously started working again. I'll close this for now, but I'll report back with more details if it stops working again.

**Comment by daviewales** [comment]
OK. I've found something that causes this issue.

When I have another mapping plugin installed, such as "MapPress Maps for WordPress", *this* plugin works fine.

When I remove the other plugin, I get errors such as the following in *this* plugin:

    The resource from “https://unpkg.com/leaflet@1.5.1/dist/leaflet.css?ver=1.5.1” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).

**Comment by goiblas** [comment]
I will include the files of the library maps in the plugin to avoid being blocked

**Comment by daviewales** [comment]
Thanks!
