### ISSUE TITLE
Allow newlines in tooltip text

### ISSUE THREAD

**Issue by daviewales** [goiblas/Map-Block-Leaflet#25]
It would be nice to be able to display newlines within the tooltip.

For example, this could be achieved by the wrapping the tooltip text in `<p>` tags, and replacing newlines with `<br>`.

**Comment by goiblas** [comment]
It's a good idea, I'm going to replace the line breaks by <br> but it scares me to use <p> like a wrapper, 
Because it may look bad because of the theme styles
