### ISSUE TITLE
Map Height Not Remembered in Block Settings

### ISSUE THREAD

**Issue by davinian** [goiblas/Map-Block-Leaflet#26]
After setting "Options > Map Height" and Publishing/Updating the Post/Page the Map does use correct height, but if you edit the Page/Post the Map Height reverts to "220".

So if you edit something on the page and Update, the Map height reverts.

Guessing the current map height is not checked when editing the Post/Page?

**Comment by goiblas** [comment]
That shouldn't happen, I'm going to check it, can you tell me which version of WordPress are you using?

**Comment by goiblas** [comment]
I can't reproduce the error, what WordPress version are you using?

**Comment by jeroensmeets** [comment]
I can reproduce it, after saving, the frontend map is ok. After editing the page, the height value has been reset to 220.

Don't see the reason for this, unfortunately. I'm on WordPress 5.2.4.

**Comment by davinian** [comment]
To confirm, I can reproduce - after editing the page the map height resets to 200.
Using latest version of WordPress.

**Comment by goiblas** [comment]
I have already reproduced it, It does not happen with the Gutenber plugin installed, I'm going to try to fix it

**Comment by davinian** [comment]
OK, so native WordPress without the Gutenberg plug-in installed is the issue?

**Comment by goiblas** [comment]
Yes

**Comment by davinian** [comment]
> Yes

OK, we at least there's a work-around, but for the websites I'm using it on the content does not change very often.

If you need anything testing, please let me know.
