### ISSUE TITLE
How can I add a two or more markers

### ISSUE THREAD

**Issue by bicho44** [goiblas/Map-Block-Leaflet#31]
There's any way we can add more than one marker?

Thanks in advance

**Comment by goiblas** [comment]
Now it is not possible to add more than one marker, do you think it can be useful?

**Comment by bicho44** [comment]
Yes.

If You have a School Campus and you wanna put in a map all the different areas. Or you have to places for the same bussiness

I have a School of English in Bariloche, who have to different sites in the same town. So for, the map, i need to show the two places in one map

I hope this help

**Comment by goiblas** [comment]
I see your point and I think that it will be useful for other people. I will develop it for the next major update.

Thanks for your contribution

**Comment by goiblas** [comment]
It is now available to add several markers in the same map, to keep it simple, it is in a new block inside the plugin
