### ISSUE TITLE
Leaflet 1.5.1 openstreetmap not working

### ISSUE THREAD

**Issue by kevinh7777** [goiblas/Map-Block-Leaflet#33]
My maps use Leaflet 1.5.1 with openstreetmap tiles.  They stopped working last week (no tiles showing).
Do I need to update to Leaflet 1.7.1?

**Comment by goiblas** [comment]
The wikipedia tiles stopped working for me too, I think it has nothing to do with the leaflet version. Try using other tiles

**Comment by goiblas** [comment]
Some providers are not working, you can see it at https://leaflet-extras.github.io/leaflet-providers/preview/.

I hope you find it helpful
