### ISSUE TITLE
Icon map don't show

### ISSUE THREAD

**Issue by fredb8x** [goiblas/Map-Block-Leaflet#55]
Hello,
the icon marker does not show on the map on the front end.
The map try to load the png from the url of the page.
`GET https://gargas-dev-front.149-202-93-199.plesk.page/fr/infos-pratiques/**marker-shadow.png** `

Thank you for your work.

**Comment by goiblas** [comment]
Hello, this icon url should be an absolute path to the map plugin folder
can you tell me the theme and plugins you are using?

**Comment by fredb8x** [comment]
Hello Jesús,
i use the plugin Oxygen builder, so i don' t have an active theme in my wordpress.
My other plugins are :
- ACF
- Asset Clean up
- Code Snippets
- CF7
- EditorsKit
- Unbloater
- WP Cerber
- Smush
- Yoast

So I think the problem comes perhaps from using Oxygen builder who is a wordpress headless.

Thank you for your help

**Comment by goiblas** [comment]
I have tried with some of those plans and it works correctly, as you say it could be because of Oxygen builder. 

I don't have Oxygen builder and I can't do any more tests. I'm sorry I can't solve it.

**Comment by fredb8x** [comment]
If you want to try with oxygen builder you can give me an adresse email, i sent you the extension.

**Comment by fredb8x** [comment]
in other way, a new implementation on your plugin should be great, the avaibility to choose a custom icon from the media library ? 
Thank you for your time Jesús

**Comment by goiblas** [comment]
Thanks for the invitation to try oxygen builder, but I am not interested.

What you said about customizing the map marker is very interesting, I have created a new issue and I will work to include it in next versions

**Comment by daviewales** [comment]
Hi @goiblas, I'm getting this issue too:
https://wollondillyanglican.org/services/

When editing the map, the tooltip has the correct URL:
https://wollondillyanglican.org/wp-content/plugins/map-block-leaflet/lib/images/marker-icon-2x.png

But when viewing the published page it is incorrect:
https://wollondillyanglican.org/services/images/marker-icon-2x.png

It used to work in the past.
