### ISSUE TITLE
Problem with html description

### ISSUE THREAD

**Issue by Nejc-Podlogar** [goiblas/Map-Block-Leaflet#59]
Hello I think there is a problem with displaying the description for the markers. 
I am currently on: Wordpress 6.5.4 and Plugin version: 3.2.0

I am using the multi marker bloc, and I added the custom marker with the correct location, in the builder i can see the display as it should be: 

![image](https://github.com/goiblas/Map-Block-Leaflet/assets/52275156/7d4022d1-8fb1-4d31-be77-cd1660f64c2d)

But when i go into preview it converts completely to text and it looks weird:

![image](https://github.com/goiblas/Map-Block-Leaflet/assets/52275156/c1521e21-3133-4130-9cb8-0a2b0a747d29)

I don't know if I am doing something wrong or not, but here are the settings for the marker:

![image](https://github.com/goiblas/Map-Block-Leaflet/assets/52275156/6bccef62-8301-4e79-81d2-778d9bb2e069)

**Comment by Nejc-Podlogar** [comment]
For the HTML not being accounted for, the problem is the **sanitize()** in render.php

For the design, I am still looking into it.

**Comment by goiblas** [comment]
Thank you for reporting the bug, I try to solve it as soon as possible.

**Comment by goiblas** [comment]
I have released a version that solves the problem of the html description.

Try it, if the rendering problems persist, send me the url and I'll check it

**Comment by Nejc-Podlogar** [comment]
Hi. 

The html tags are rendered correctly, but the overall display of the popup when i publish (in the builder they are displayed correctly) is still broken:

![image](https://github.com/goiblas/Map-Block-Leaflet/assets/52275156/5baa4303-daf1-42b1-a73f-19d286546a2c)


I have added the map to a site that is currently not used. So you can check for yourself
[https://zlet.taborniki.si/pomembni-datumi/](https://zlet.taborniki.si/pomembni-datumi/)

**Comment by Nejc-Podlogar** [comment]
Never mind. The theme is the problem for the display of the popup. I need to update the theme. I think the plugin works okay. ( i changed to another theme and it displays correctly)
